apiVersion: v1
kind: Secret
metadata:
  name: mogbank-secrets
  namespace: mogbank
  labels:
    app: mogbank
type: Opaque
stringData:
  # Database
  DB_PASSWORD: "{{ .Values.db.password }}"

  # Redis
  REDIS_PASSWORD: "{{ .Values.redis.password }}"

  # JWT
  JWT_SECRET: "{{ .Values.auth.jwtSecret }}"

  # x402 Private Key
  X402_PRIVATE_KEY: "{{ .Values.crypto.x402PrivateKey }}"
